---
engines:
 rubocop:
 enabled: true
 exclude_paths:
 - config/engines.yml
 duplication:
 enabled: true
 exclude_paths:
 - config/engines.yml
 metrics:
 enabled: true
 exclude_paths:
 - config/engines.yml
 coverage:
 enabled: true
 exclude_paths:
 - config/engines.yml
languages:
 css:
 extensions:
 - '-css.resource'
exclude_paths:
 - 'README.md'
 - 'js/lib/angular.js'
 - 'js/lib/angular-idle.min.js'